{% set name = "HandyReadGenotyper" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AntonS-bio/HandyReadGenotyper/archive/{{ version }}.tar.gz
  sha256: fdb514deaf7b9c483bef48e1f1bf955d948697e78ef128aaf41e198c0fc38f6e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  run_exports:
      - {{ pin_subpackage('handyreadgenotyper', max_pin="x.x") }}  
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pandas >=2.0.0
    - scikit-learn >=1.3.*
    - pysam >=0.22.0
    - numpy >=1.20.*
    - tqdm >=4.66.*
    - biopython >=1.78

test:
  commands:
    - classify -h
    - train -h
  requires:
    - pip

about:
  license: GPL-3.0
  license_file: LICENSE
  home: https://github.com/AntonS-bio/HandyReadGenotyper
  summary: 'Tool for training model and classifying reads from environmental ONT amplicon sequencing.'
  description: |
    Tool for training model and classifying reads from environmental ONT amplicon sequencing. 
  doc_source_url: https://github.com/AntonS-bio/HandyAmpliconTool/blob/main/README.md


extra:
  recipe-maintainers:
    - AntonS-bio
