{% set name = "AmpliconTyper" %}
{% set version = "0.1.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AntonS-bio/AmpliconTyper/archive/{{ version }}.tar.gz
  sha256: c78f26616d7355f323bf9b6f416c13b276d9ff71816bdc5bc02d1f2d6f95e0a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  run_exports:
      - {{ pin_subpackage('amplicontyper', max_pin="x.x") }}  
  number: 0

requirements:
  host:
    - pip
    - python >=3.10
  run:
    - python >=3.10
    - pandas >=2.0.0
    - scikit-learn >=1.3.*
    - pysam >=0.22.0
    - numpy >=1.20.*
    - tqdm >=4.66.*
    - biopython >=1.78
    - minimap2
    - samtools

test:
  commands:
    - train -h
    - classify -h
  requires:
    - pip

about:
  license: GPL-3.0-only
  license_file: LICENSE
  home: https://github.com/AntonS-bio/AmpliconTyper
  summary: 'Tool for training model and classifying reads from environmental ONT amplicon sequencing.'
  description: |
    Tool for training model and classifying reads from environmental ONT amplicon sequencing. 
  doc_source_url: https://github.com/AntonS-bio/AmpliconTyper/blob/main/README.md


extra:
  recipe-maintainers:
    - AntonS-bio
